Repository dataplat/dbatools, pull requests merged in 2018-04, with the labels that each got.

#3492 Fix restoring simple model dbs with diffs
  appveyor.yml
  bin/dbatools.dll
  bin/dbatools.pdb
  bin/dbatools.xml
  bin/library.ps1
  bin/projects/dbatools/dbatools/Database/BackupHistory.cs
  bin/projects/dbatools/dbatools/Properties/AssemblyInfo.cs
  functions/Get-DbaBackupHistory.ps1
  functions/Get-DbaBackupInformation.ps1
  functions/Invoke-DbaAdvancedRestore.ps1
  tests/Restore-DbaDatabase.Tests.ps1
Labels: bugs_life

#3530 Added validation attributes
  bin/dbatools.dll
  bin/dbatools.pdb
  bin/dbatools.xml
  bin/projects/dbatools/dbatools/Utility/DbaValidatePatternAttribute.cs
  bin/projects/dbatools/dbatools/Utility/DbaValidateScriptAttribute.cs
  bin/projects/dbatools/dbatools/dbatools.csproj
  bin/typealiases.ps1
Labels: Status: Review Needed, Type: Enhancement, awesome_sauce

#3531 Install-DbaFirstResponderKit - Included TLS protocol override
  functions/Install-DbaFirstResponderKit.ps1
Labels: Status: Review Needed, Type: Bug, bugs_life

#3562 Two new commands
  functions/Get-DbaDbCheckConstraint.ps1
  functions/Get-DbaDbForeignKey.ps1
  tests/Get-DbaDbCheckConstraint.Tests.ps1
  tests/Get-DbaDbForeignKey.Tests.ps1
Labels: brand-spanking-new
