Repository dataplat/dbatools, pull requests merged in 2018-11, with the labels that each got.

#4405 Fix improve expand dba t log responsibly
  functions/Expand-DbaTLogResponsibly.ps1
  tests/Expand-DbaTLogResponsibly.Tests.ps1
Labels: Feature, bugs_life

#4431 Cope with recovery forks in backup history
  functions/Get-DbaBackupHistory.ps1
  tests/Get-DbaBackupHistory.Tests.ps1
Labels: bugs_life

#4565 Memory commands fix
  functions/Get-DbaDbMemoryUsage.ps1
  functions/Get-DbaMemoryUsage.ps1
Labels: bugs_life

#4573 Fixes #3443- Exclude 'user mapped to a certificate' from OrphanUsers
  functions/Get-DbaOrphanUser.ps1
  functions/Remove-DbaOrphanUser.ps1
  functions/Repair-DbaOrphanUser.ps1
Labels: bugs_life

#4700 Agent server new commands
  functions/Get-DbaAgentServer.ps1
  functions/Set-DbaAgentServer.ps1
  tests/Get-DbaAgentServer.Tests.ps1
  tests/Set-DbaAgentServer.Tests.ps1
Labels: Feature

#4711 pushing recoveryfork into history from backup
  functions/Backup-DbaDatabase.ps1
Labels: bugs_life

#4687 New function - Update-DbaInstance
  functions/Get-DbaBuildReference.ps1
  functions/Test-DbaBuild.ps1
  functions/Update-DbaInstance.ps1
  internal/configurations/settings/remoting.ps1
  internal/functions/Find-SqlServerUpdate.ps1
  internal/functions/Get-SqlInstanceComponent.ps1
  internal/functions/Get-SqlServerVersion.ps1
  internal/functions/Initialize-CredSSP.ps1
  internal/functions/Install-SqlServerUpdate.ps1
  internal/functions/Invoke-Command2.ps1
  internal/functions/Invoke-Program.ps1
  internal/functions/Register-RemoteSessionConfiguration.ps1
  internal/functions/Restart-WinRMService.ps1
  internal/functions/Test-PendingReboot.ps1
  internal/functions/Unregister-RemoteSessionConfiguration.ps1
  tests/Get-DbaBuildReference.Tests.ps1
  tests/Update-DbaInstance.Tests.ps1
Labels: Feature
