Repository dataplat/dbatools, pull requests merged in 2018-03, with the labels that each got.

#3302 DbaDatabase & DbaDatabaseSmo parameter classes
  bin/dbatools.dll
  bin/dbatools.pdb
  bin/dbatools.xml
  bin/library.ps1
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.Tests.dll
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.Tests.pdb
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.dll
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.pdb
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.xml
  bin/projects/dbatools/dbatools/Parameter/DbaDatabaseParameter.cs
  bin/projects/dbatools/dbatools/Parameter/DbaDatabaseSmoParameter.cs
  bin/projects/dbatools/dbatools/Properties/AssemblyInfo.cs
  bin/projects/dbatools/dbatools/dbatools.csproj
  bin/typealiases.ps1
Labels: P3 - On Fire, Status: Review Needed, Type: Enhancement, awesome_sauce

#3344 New Command: Find-DbaInstance
  bin/dbatools.dll
  bin/dbatools.pdb
  bin/dbatools.xml
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.Tests.dll
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.Tests.pdb
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.dll
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.pdb
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.xml
  bin/projects/dbatools/dbatools/Discovery/DbaBrowserReply.cs
  bin/projects/dbatools/dbatools/Discovery/DbaInstanceAvailability.cs
  bin/projects/dbatools/dbatools/Discovery/DbaInstanceConfidenceLevel.cs
  bin/projects/dbatools/dbatools/Discovery/DbaInstanceDiscoveryType.cs
  bin/projects/dbatools/dbatools/Discovery/DbaInstanceReport.cs
  bin/projects/dbatools/dbatools/Discovery/DbaInstanceScanType.cs
  bin/projects/dbatools/dbatools/Discovery/DbaPortReport.cs
  bin/projects/dbatools/dbatools/Parameter/DbaInstanceParameter.cs
  bin/projects/dbatools/dbatools/dbatools.csproj
  dbatools.psd1
  functions/Find-DbaInstance.ps1
  internal/functions/Invoke-SteppablePipeline.ps1
  xml/dbatools.Format.ps1xml
Labels: P3 - On Fire, Status: Review Needed, Type: New Command, awesome_sauce

#3382 Find-DbaInstance - Fixed scans and added validation for invalid scans
  functions/Find-DbaInstance.ps1
Labels: P3 - On Fire, Status: Review Needed, Type: Bug, bugs_life

#3383 Making dbasize great again! (again)
  bin/dbatools.dll
  bin/dbatools.pdb
  bin/dbatools.xml
  bin/library.ps1
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.Tests.dll
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.Tests.pdb
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.dll
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.pdb
  bin/projects/dbatools/dbatools.Tests/bin/Debug/dbatools.xml
  bin/projects/dbatools/dbatools/Properties/AssemblyInfo.cs
  bin/projects/dbatools/dbatools/Utility/Size.cs
  bin/projects/dbatools/dbatools/Utility/SizeStyle.cs
  bin/projects/dbatools/dbatools/Utility/UtilityHost.cs
  bin/projects/dbatools/dbatools/dbatools.csproj
  internal/configurations/settings/formatting.ps1
  internal/configurations/validation/sizestyle.ps1
Labels: Status: Review Needed, Type: Enhancement, awesome_sauce

#3397 Get-DbaUserLevelPermission - Reset $serverDT for next Instance
  functions/Get-DbaUserLevelPermission.ps1
Labels: Type: Bug

#3410 skip backup file on version mismatch
  functions/Read-DbaBackupHeader.ps1
Labels: bugs_life

#3433 Find-SqlInstance: Fixed interpretation of SPNs that point at named instances
  functions/Find-DbaInstance.ps1
Labels: P3 - On Fire, Status: Review Needed, bugs_life
