Repository dataplat/dbatools, pull requests merged in 2018-07, with the labels that each got.

#3745 Select-DbaObject: Tests and documentation
  functions/Select-DbaObject.ps1
  tests/Select-DbaObject.Tests.ps1
Labels: Status: Review Needed

#3747 Fixed logic
  functions/Start-DbaAgentJob.ps1
Labels: bugs_life

#3748 Get-DbaCredential: Support for list of instances
  functions/Get-DbaCredential.ps1
Labels: Status: Review Needed, bugs_life

#3727 Adding time filtering before scanning for Maintenance Plan backups
  functions/Get-DbaBackupInformation.ps1
  functions/Restore-DbaDatabase.ps1
  tests/Get-DbaBackupInformation.Tests.ps1
Labels: Type: Enhancement

#3767 Select-DbaObject : Set Typename, pick defaultview
  functions/Select-DbaObject.ps1
Labels: Status: Review Needed, Type: Enhancement, awesome_sauce

#3783 Stop-Function: Hid warning with exception
  bin/dbatools.dll
  bin/dbatools.pdb
  bin/projects/dbatools/dbatools/Commands/WriteMessageCommand.cs
  internal/functions/Stop-Function.ps1
Labels: Type: Bug, bugs_life

#3796 Message bugfix
  dbatools.psd1
  dbatools.psm1
  internal/scripts/message-transforms.ps1
Labels: Status: Review Needed, Type: Bug, awesome_sauce, bugs_life

#3793 Fixed Test-DbaWindowsLogin so it copes with Computer accounts
  functions/Test-DbaWindowsLogin.ps1
Labels: Type: Enhancement

#3843 Fixed import bug on psv3
  bin/dbatools.dll
  bin/dbatools.pdb
  bin/dbatools.xml
  bin/projects/dbatools/dbatools/Commands/WriteMessageCommand.cs
  bin/projects/dbatools/dbatools/Utility/UtilityHost.cs
Labels: P3 - On Fire, bugs_life
