Repository dataplat/dbatools, pull requests merged in 2018-02, with the labels that each got.

#3219 DbaInstanceParameter: Added support for plain (localdb) strings
  bin/dbatools.dll
  bin/dbatools.pdb
  bin/library.ps1
  bin/projects/dbatools/dbatools/Parameter/DbaInstanceParameter.cs
  bin/projects/dbatools/dbatools/Properties/AssemblyInfo.cs
Labels: Status: Review Needed, Type: Enhancement

#3270 Inmem
  functions/Test-DbaBackupInformation.ps1
Labels: bugs_life

#3294 Write-DbaDataTable: Fixed Red Exception of Doom
  functions/Write-DbaDataTable.ps1
Labels: Status: Review Needed, Type: Bug, bugs_life

#3304 Issue 3275 - Copy-DbaLinkedServer Providers Incorrect
  functions/Copy-DbaLinkedServer.ps1
  tests/Copy-DbaLinkedServer.Tests.ps1
Labels: Status: Review Needed
