Repository dataplat/dbatools, pull requests merged in 2019-05, with the labels that each got.

#5474 Restore Tests fixed
  tests/Copy-DbaDatabase.Tests.ps1
  tests/Restore-DbaDatabase.Tests.ps1
Labels: bugs_life

#5519 Start-DbaAgentJob Verbose shoe round 2
  functions/Start-DbaAgentJob.ps1
Labels: bugs_life, solution provided

#5570 New Function Get-DbaDbObjectTrigger & Improve Find-DbaTrigger
  functions/Find-DbaTrigger.ps1
  functions/Get-DbaDbObjectTrigger.ps1
  tests/Get-DbaDbObjectTrigger.Tests.ps1
Labels: Feature

#5475 Restfixes
  functions/Invoke-DbaAdvancedRestore.ps1
  tests/Copy-DbaDatabase.Tests.ps1
  tests/Restore-DbaDatabase.Tests.ps1
Labels: bugs_life
