Repository dataplat/dbatools, pull requests merged in 2020-02, with the labels that each got.

#6348 Find-DbaInstance - not finding on custom port
  bin/net452/dbatools.dll
  bin/net452/dbatools.pdb
  bin/netcoreapp2.1/dbatools.dll
  bin/netcoreapp2.1/dbatools.pdb
  bin/projects/dbatools/dbatools/Discovery/DbaInstanceReport.cs
Labels: bugs_life

#6350 Improve Export-Dba* output
  functions/Export-DbaUser.ps1
  tests/Export-DbaUser.Tests.ps1
Labels: Confirmed, Documentation, bugs_life

#6383 Improve datamasking performance
  functions/Invoke-DbaDbDataMasking.ps1
  tests/Invoke-DbaDbDataMasking.Tests.ps1
Labels: Feature, bugs_life
