Repository dataplat/dbatools, pull requests merged in 2020-11, with the labels that each got.

#6950 Improve Export-DbaUser
  functions/Export-DbaUser.ps1
  tests/Export-DbaUser.Tests.ps1
Labels: bugs_life

#6948 Add option to ignore diff backups when using Test-DbaLastBackup
  dbatools(1).dll
  dbatools.psm1
  functions/Get-DbaDbBackupHistory.ps1
  functions/Test-DbaLastBackup.ps1
  tests/Get-DbaDbBackupHistory.Tests.ps1
  tests/Test-DbaLastBackup.Tests.ps1
Labels: Feature

#6984 fix docs on command Get-DbaProductKey
  functions/Get-DbaProductKey.ps1
Labels: Documentation, bugs_life
